### ISSUE TITLE
Barding

### ISSUE THREAD

**Issue by FromTheGrayve** [foophoof/CollectorsAnxiety#11] opened 2023-10-21 14:56 UTC
Chocobo barding does not seem to track correctly, It shows I have 46/91, but when I equip a set CA thinks is missing, it updates to 44/91 but the barding still stays on the list. If i put on another piece it goes to 43/91 

And just equpping or unequpping gear on the chocobo seems to confuse it, its now saying i have 35/91

Ive checked it both in housing area and in overworld. 

For the record, on lala achievements i show i have 77 of 78   

Not sure why CA shows more items then Lalaachievments.

**Comment by foophoof** [comment] 2024-07-13 23:16
I'm not able to reproduce this on the latest version, could you please try to see if it's reproducible still on your end?

**Comment by FromTheGrayve** [comment] 2024-07-15 13:41
uh this was posted almost a year ago, but ill check in about 24 hours. Working till then.

**Comment by foophoof** [comment] 2024-07-15 14:10
Yeah, sorry for the necro bump, I just recently adopted this plugin so I'm just going through the issues to see which are still valid and which have since been fixed.

**Comment by FromTheGrayve** [comment] 2024-07-17 01:58
Sorry had PC issues, testing now

**Comment by FromTheGrayve** [comment] 2024-07-17 03:01
It appears to be working, showing 91//96 and not changing when i change my chocobos barding

**Comment by FromTheGrayve** [comment] 2024-07-17 03:01
if i collect more later ill let you know how it goes

**Comment by foophoof** [comment] 2024-11-16 16:04
Closing this then, but please do reopen/file a new issue if it ends up being broken again.

**Closed by foophoof** 2024-11-16 16:04 UTC
